log4cplus.rootLogger=TRACE, fileAppender, consoleAppender

log4cplus.appender.fileAppender=log4cplus::RollingFileAppender
log4cplus.appender.fileAppender.MaxFileSize=1MB
log4cplus.appender.fileAppender.MaxBackupIndex=1
log4cplus.appender.fileAppender.layout=log4cplus::PatternLayout
log4cplus.appender.fileAppender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S.%q} [%t] %-5p %c - %m%n%n
log4cplus.appender.fileAppender.File=../logs/client.log

log4cplus.appender.consoleAppender=log4cplus::ConsoleAppender
log4cplus.appender.consoleAppender.Target=System.out
log4cplus.appender.consoleAppender.layout=log4cplus::PatternLayout
log4cplus.appender.consoleAppender.layout.ConversionPattern=%D{%Y-%m-%d %H:%M:%S.%q} [%t] %-5p %c - %m%n%n
